const products = [
  {
    title: "Magnetite",
    category: 1,
    price: 89.0,
    img: "./assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorar",
    category: 2,
    price: 66.0,
    img: "./assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 8,
    price: 50.0,
    img: "./assets/img/3.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 4,
    price: 22.0,
    img: "./assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "Toxicity",
    category: 8,
    price: 35.0,
    img: "./assets/img/5.jpg",
    band: "System Of A Down",
    year: 2001,
    id: 4,
  },
  {
    title: "The Last Hero",
    category: 8,
    price: 47.0,
    img: "./assets/img/6.jpg",
    band: "Alter Bridge",
    year: 2016,
    id: 5,
  },
  {
    title: "Acústico MTV",
    category: 2,
    price: 34.0,
    img: "./assets/img/7.jpg",
    band: "Os Paralamas do Sucesso",
    year: 1999,
    id: 6,
  },
  {
    title: "Octavarium",
    category: 8,
    price: 75.0,
    img: "./assets/img/8.jpg",
    band: "Dream Theater",
    year: 2005,
    id: 7,
  },
  {
    title: "Na Pressão",
    category: 2,
    price: 49.0,
    img: "./assets/img/9.jpg",
    band: "Lenine",
    year: 1999,
    id: 8,
  },
  {
    title: "5 a Seco - Ao Vivo",
    category: 2,
    price: 35.0,
    img: "./assets/img/10.jpg",
    band: "5 a Seco",
    year: 2012,
    id: 9,
  },
  
];

const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Baião",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];

